# Numpy

**Properties**

- `ndim`
- `size`
- `shape`

**Functions**

Basics `np.function(x)`
- `array()`
- `arange()`
- `reshape()`*

Manipulating `np.function(x)`
- `append()`
- `delete()`
- `sort()`

Operations `x.function()`
- `sum()`
- `min()`
- `max()`

Statistics `np.function(x)`
- `mean()`
- `median()`
- `var()`
- `std()`

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# x[1][2] == x[1, 2]

print(x.ndim, x.size, x.shape)

2 9 (3, 3)


In [3]:
x = np.array([2, 1, 3])

x = np.append(x, 4)
print(x)

# deletes the element in the index given
x = np.delete(x, 2)
print(x)

x = np.sort(x)
print(x)

[2 1 3 4]
[2 1 4]
[1 2 4]


In [4]:
x = np.arange(1, 7, 1)
print(x)

z = x.reshape((3, 2))
print(z)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
x = np.arange(1, 10)
print(x)
print(x[0:2])
print(x[-3:])


[1 2 3 4 5 6 7 8 9]
[1 2]
[7 8 9]


In [6]:
x = np.arange(1, 10)

y = (x > 5) & (x % 2 == 0)

print(x, x[y])

[1 2 3 4 5 6 7 8 9] [6 8]


In [7]:
x = np.arange(1, 10)
x, x.sum()

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 45)

In [8]:
x = np.arange(1, 10)
y = x*2
x, y

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [9]:
x = np.array([14, 18, 19, 24, 26, 33, 42, 55, 67])
print(np.mean(x), np.median(x), np.var(x), np.std(x))

33.111111111111114 26.0 292.5432098765432 17.10389458212787


# House Prices

You are given an array that represents house prices.

Calculate and output the percentage of houses that are within one standard deviation from the mean.

- To calculate the percentage, divide the number of houses that satisfy the condition by the total number of houses, and multiply the result by 100.

In [10]:
data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

std = np.std(data)
mean = np.mean(data)

between = ((mean - std) <= data) & (data <= (mean + std))

slice_arr = data[between]

print(slice_arr.size / data.size * 100) 

62.5
